micronaut:
  application:
    name: ms-java-mallplaza

datasources:
  default:
    url: 'jdbc:h2:mem:jhipstersampleapplication;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'JhipsterSampleApplication'
    password: ''
    driver-class-name: org.h2.Driver
    dialect: H2
liquibase:
  datasources:
    default:
      enable: true
      change-log: 'classpath:db/liquibase-changelog.xml'

jpa:
  default:
    entity-scan:
      packages: 'com.mallplaza.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
